modLoader="javafml"
loaderVersion="[41,)"
license="LGPL v2.1"
[[mods]]
modId="l2artifacts"
version="${file.jarVersion}" #mandatory
displayName="L2 Artifacts" #mandatory
logoFile="l2artifacts.png" #optional
credits="Thanks to GenshinImpact for ideas" #optional
authors="lcy0x1 and LightLand team" #optional
description='''
Genshin Impact style artifacts that helps to boost player stats.
'''
[[dependencies.l2artifacts]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.l2artifacts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2artifacts]]
    modId="attributefix"
    mandatory=true
    versionRange="[17,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.l2artifacts]]
    modId="maxhealthfix"
    mandatory=true
    versionRange="[8,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.l2artifacts]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.l2artifacts]]
    modId="l2library"
    mandatory=true
    versionRange="[2.2.0,)"
    ordering="AFTER"
    side="BOTH"