modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="l2artifacts"
version="${file.jarVersion}" #mandatory
displayName="Player Difficulty" #mandatory
logoFile="l2artifacts.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2artifacts]]
    modId="forge"
    mandatory=true
    versionRange="[40.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.l2artifacts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2artifacts]]
    modId="l2library"
    mandatory=true
    versionRange="[0.0.8,)"
    ordering="AFTER"
    side="BOTH"